name: Shanika Galaudage

description: I am an astrophysics PhD candidate at Monash University. My primary interests are gravitational waves and compact objects, specifically how using gravitational waves can help us understand more about the population of these compact objects in the Universe.  I am a member of OzGrav - Australian Research Council Centre of Excellence for Gravitational Wave Discovery, and a member of the LIGO Scientific Collaboration. (My webpage is currently under construction.)

